# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Adhoc Build"
  desc "This will also make sure the profile is up to date"
  lane :adhoc do
    match(type: "adhoc", readonly: is_ci)
    gym(scheme: "prod")
    sh("python", "firebase/prepareDeploy.py")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "adhoc", readonly: is_ci)
    gym(scheme: "prod")
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore", readonly: is_ci)
    # snapshot
    gym(scheme: "prod")
    deliver(force: true)
    # frameit
  end

  desc "Deploy a new version to Firebase Distribution"
  lane :firebase_distribution do
      match(type: "adhoc", readonly: is_ci)

      gym(scheme: "prod")

      firebase_app_distribution(
          app: "1:1037152984459:ios:7a0b733b3b4a95ed03a38e",
          testers: "debruyn.sarel@gmail.com, amyuc91@gmail.com",
          release_notes: "Please test iOS features and report new issues to debruyn.sarel@gmail.com",
          firebase_cli_path: "/Users/cdebruyn/.nvm/versions/node/v13.9.0/bin/firebase"
      )

  end

  desc "Download and install all the code signing certificates needed."
  lane :certificates do 
    match(git_url: "git@gitlab.com:4-the-people/ios-certificates.git", type: "development", app_identifier: "com.forthepeople.uncovid.dev")
    match(git_url: "git@gitlab.com:4-the-people/ios-certificates.git", type: "adhoc")
    match(git_url: "git@gitlab.com:4-the-people/ios-certificates.git", type: "appstore", app_identifier: "com.forthepeople.uncovid")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
