# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  desc "Deploy a new version to Firebase Distribution"
  lane :firebase_distribution do
    gradle(
      task: "assemble",
      flavor: "prod",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_SIGNING_KEY_FILE"],
        "android.injected.signing.store.password" => "CD-5g@Ng96d094e8Poes",
        "android.injected.signing.key.alias" => "uncovid-key",
        "android.injected.signing.key.password" => "CD-5g@Ng96d094e8Poes",
      }
    )

    firebase_app_distribution(
        apk_path: ENV["RELEASE_APK_PATH"],
        app: "1:1037152984459:android:9b4d7c73a67eec9203a38e",
        testers: "debruyn.sarel@gmail.com, trismaske@gmail.com",
        release_notes: "Please test Android features and report new issues to debruyn.sarel@gmail.com",
        firebase_cli_path: ENV["FIREBASE_CLI_PATH"]
    )

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
